# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syntaxUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1743, 894)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit_Code = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Code.setGeometry(QtCore.QRect(960, 40, 741, 501))
        self.plainTextEdit_Code.setObjectName("plainTextEdit_Code")
        self.pushButton_readSyntax = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readSyntax.setGeometry(QtCore.QRect(20, 30, 231, 51))
        self.pushButton_readSyntax.setObjectName("pushButton_readSyntax")
        self.tabWidget_Action = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Action.setGeometry(QtCore.QRect(270, 20, 671, 821))
        self.tabWidget_Action.setObjectName("tabWidget_Action")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.plainTextEdit_syntaxRule = QtWidgets.QPlainTextEdit(self.tab_6)
        self.plainTextEdit_syntaxRule.setGeometry(QtCore.QRect(0, 0, 671, 791))
        self.plainTextEdit_syntaxRule.setObjectName("plainTextEdit_syntaxRule")
        self.tabWidget_Action.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableView_Action = QtWidgets.QTableView(self.tab_2)
        self.tableView_Action.setGeometry(QtCore.QRect(0, 0, 671, 791))
        self.tableView_Action.setObjectName("tableView_Action")
        self.tabWidget_Action.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.plainTextEdit_SysOutput = QtWidgets.QPlainTextEdit(self.tab_7)
        self.plainTextEdit_SysOutput.setGeometry(QtCore.QRect(0, 0, 671, 791))
        self.plainTextEdit_SysOutput.setObjectName("plainTextEdit_SysOutput")
        self.tabWidget_Action.addTab(self.tab_7, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView_GOTO = QtWidgets.QTableView(self.tab)
        self.tableView_GOTO.setGeometry(QtCore.QRect(0, 0, 671, 791))
        self.tableView_GOTO.setObjectName("tableView_GOTO")
        self.tabWidget_Action.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableView_SELECT = QtWidgets.QTableView(self.tab_3)
        self.tableView_SELECT.setGeometry(QtCore.QRect(0, 0, 671, 791))
        self.tableView_SELECT.setObjectName("tableView_SELECT")
        self.tabWidget_Action.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableView_FOLLOW = QtWidgets.QTableView(self.tab_4)
        self.tableView_FOLLOW.setGeometry(QtCore.QRect(0, 0, 671, 791))
        self.tableView_FOLLOW.setObjectName("tableView_FOLLOW")
        self.tabWidget_Action.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableView_FIRST = QtWidgets.QTableView(self.tab_5)
        self.tableView_FIRST.setGeometry(QtCore.QRect(0, 0, 671, 791))
        self.tableView_FIRST.setObjectName("tableView_FIRST")
        self.tabWidget_Action.addTab(self.tab_5, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(960, 560, 221, 41))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(960, 760, 221, 41))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.pushButton_readCode = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readCode.setGeometry(QtCore.QRect(20, 110, 231, 51))
        self.pushButton_readCode.setObjectName("pushButton_readCode")
        self.pushButton_analyze = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_analyze.setGeometry(QtCore.QRect(20, 270, 231, 51))
        self.pushButton_analyze.setObjectName("pushButton_analyze")
        self.pushButton_generatePDF = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_generatePDF.setGeometry(QtCore.QRect(20, 350, 231, 51))
        self.pushButton_generatePDF.setObjectName("pushButton_generatePDF")
        self.plainTextEdit_Error = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Error.setGeometry(QtCore.QRect(960, 640, 731, 111))
        self.plainTextEdit_Error.setObjectName("plainTextEdit_Error")
        self.pushButton_readWrong = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readWrong.setGeometry(QtCore.QRect(20, 190, 231, 51))
        self.pushButton_readWrong.setObjectName("pushButton_readWrong")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1743, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_Action.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_readSyntax.setText(_translate("MainWindow", "读取文法"))
        self.tabWidget_Action.setTabText(self.tabWidget_Action.indexOf(self.tab_6), _translate("MainWindow", "文法"))
        self.tabWidget_Action.setTabText(self.tabWidget_Action.indexOf(self.tab_2), _translate("MainWindow", "ACTION表"))
        self.tabWidget_Action.setTabText(self.tabWidget_Action.indexOf(self.tab_7), _translate("MainWindow", "系统输出"))
        self.tabWidget_Action.setTabText(self.tabWidget_Action.indexOf(self.tab), _translate("MainWindow", "GOTO表"))
        self.tabWidget_Action.setTabText(self.tabWidget_Action.indexOf(self.tab_3), _translate("MainWindow", "文法SELECT集"))
        self.tabWidget_Action.setTabText(self.tabWidget_Action.indexOf(self.tab_4), _translate("MainWindow", "文法FOLLOW集"))
        self.tabWidget_Action.setTabText(self.tabWidget_Action.indexOf(self.tab_5), _translate("MainWindow", "文法FIRST集"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">代码视图</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">错误信息</span></p></body></html>"))
        self.pushButton_readCode.setText(_translate("MainWindow", "读取源码(正例)"))
        self.pushButton_analyze.setText(_translate("MainWindow", "文法分析"))
        self.pushButton_generatePDF.setText(_translate("MainWindow", "生成可视化树状图"))
        self.pushButton_readWrong.setText(_translate("MainWindow", "读取源码(反例)"))
